# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['df', 'df1', 'df2', 'prepare_dataframes']

# %% ../nbs/00_core.ipynb 3
from nbdev.showdoc import *
import pandas as pd

# %% ../nbs/00_core.ipynb 4
def prepare_dataframes():
    data = [10,20,30,40,10,20,30,40,50]
    df = pd.DataFrame(data, columns=['Numbers'])
    
    data1 = [12,21,31,12,13,54,32,21,12]
    df1 = pd.DataFrame(data1, columns=['Numbers1'])
    return df, df1

# %% ../nbs/00_core.ipynb 5
df, df1 = prepare_dataframes()

# %% ../nbs/00_core.ipynb 8
df2 = pd.concat([df,df1], axis=1)
df2
