# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_issue2.ipynb.

# %% auto 0
__all__ = ['some_method', 'methods']

# %% ../nbs/01_issue2.ipynb 2
import pandas as pd

# %% ../nbs/01_issue2.ipynb 3
def some_method(a,b):
    return a+b

# %% ../nbs/01_issue2.ipynb 4
class methods:
    def __init__(self,a):
        self.a = a
    def sum_method(self, b):
        return self.a + b
